### ISSUE TITLE
Restrict panning to area

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.panzoom.js#14]
Its often useful to restrict the panning to a specified area so people dont move the object out of the canvas.

For this I propose the following api:

```
el.panZoom({
  area: SVG.Box(x, y, width, height)
})
```

It has to be noted that the values passed must match for the zoom lvl 1. Restrictions for other zoom levels are calculated on the fly.

That means that the area expands when zooming in and shrinks when zooming out. Otherwise people could not pan to specific points when zoomed in. For shrinking it might be useful to stay at the canvas size for the minimal area

**Comment by inanisvitae** [comment]
Hey,
when will this api be implemented?

**Comment by Fuzzyma** [comment]
We are short on time atm. So this wont be done before end of 2017 - sorry. However you can give it a try and create a PR. That would be awesome!

**Comment by palodelincak** [comment]
Any progress on this feature please?

**Comment by Fuzzyma** [comment]
No sorry. Its rather complicated to implement and there was no time to do it

**Comment by pjfsilva** [comment]
I'm also trying to work out on something like this (I think). I was using svg-pan-zoom library and they have this demo on limiting pan: http://ariutta.github.io/svg-pan-zoom/demo/limit-pan.html

Is that the goal we are trying to achieve here? 

At first it seems rather easy to do, just change the panning method (line 166) to do some kind of IF condition checks according to some new options like

`if (box.x < options.minX) 
  box.x = options.minX`

A quick & dirty test seems like this works. A further refinement should be done so that when we zoom out, the box limits are also enforced.

Is there something else that complicates this? For reference we can also look at the mention svg-pan-zoom library.

**Comment by Fuzzyma** [comment]
If you think you found a good way to do it, go ahead and give it a try. I would really like to have this feature but somehow I got stuck in nowhere. Your contribution is really appreciated!

**Comment by pjfsilva** [comment]
My idea is basically this: https://jsfiddle.net/95msu3jf/

It's not perfect because zoomIn/out should also enforce those min/max values but for panning seems to work good enough. 

Changes were done on the panning method. (it's a quick and dirty approach, options should be properly handled)

Feedback?

**Comment by Fuzzyma** [comment]
Interesting! Your restriction is in the zoomed coordinate system so the restriction zooms with the area. Thats actually a good idea.
Zoom should really enforce the values but I think thats easily possible, too.

Nice work! When you wrap that up that as a PR we can merge it.

**Comment by burnetst** [comment]
Question, notice in this jsfiddle example, pan restriction is working while the svg is at scale or zoomed out. However when zoomed in you can no longer pan.

Would like a way to zoom in and still be able to pan whilst keeping the edges of the svg locked to the edges of the viewbox.

Link: https://jsfiddle.net/hefys2gc/

Any help much is appreciated!

**Comment by Fuzzyma** [comment]
Well you restrict the pan to teh edges so when you touch an edge you cannot move. And when every edge touches, you cant move in any direction. So you have to reverse the logic for that case. However, this is more a question for stackoverflow and not for an issue tracker

**Comment by Fuzzyma** [comment]
An `margins` option to restrict the pan area has been added with 232cd9ad853447c17ceba7e3d77d345a0bbcb801

It is an object with `top, left, bottom, right` properties that specifies how much of the area has to be still in the viewport after panning.

```js
canvas.panZoom({
  margins: {
    top: 100,
    left: 200,
    bottom: -Infinity, // basically disables this one
    top: 300
  }
})
```

The margins do not change with zoom so they stay always the same. As a rule of thumb, the unit is in screen px or in svg coords with` zoom==1`
