### ISSUE TITLE
One finger pan

### ISSUE THREAD

**Issue by bnjm** [svgdotjs/svg.panzoom.js#30]
Is it currently possible to enable single finger panning with this plugin? Or is there an alternate way to achieve this with SVG.js? 

If not it would be a great addition to the library, I'd be happy to make a PR if pointed in the right direction.

**Comment by Fuzzyma** [comment]
No its not possible. One finger panning is usually used to pan the webpage itself. Overloading it with an svg pan would make panning of the page impossible in that region. Additionally the browser has to wait for your event get handled before it can decide what to do. That slows down responsivness and feels strange. Furthermore panning and zooming with 2 fingers go hand in hand.

Because of the reasons listed above it was not implemented.

**Comment by bnjm** [comment]
Great points. The use-case for one finger panning would be a web app where none of the parents of the svg element are scrollable. The main example of this is maps.google.com, which uses one finger pan. Additionally I think some of the mentioned issues are already present in the plugin by capturing the mousewheel event, which can prevent scrolling of the parent. So plugin consumers already need to be aware of these issues.

**Comment by Fuzzyma** [comment]
You got some points there. Implementing it is certainly possible. I just dont know how it would interfer with the other functionalities. But you can give it a try. I think the best guidance is the code itself :D.

**Comment by Fuzzyma** [comment]
Enable it with the `oneFingerPan: true` option
